const GET_ALL_MOVIES = "GET_ALL_MOVIES";
const GET_MOVIES_SELECTED = "GET_MOVIES_SELECTED";
const GET_GENRES_MOVIES  = "GET_GENRES_MOVIES ";
const GET_MOVIES_GENRES_SELECTED = "GET_MOVIES_GENRES_SELECTED";
const GET_QUERY = "GET_QUERY";
const QUERY_INPUT = "QUERY_INPUT";
const ADD_BOOKMARK = "ADD_BOOKMARK";
const GET_BOOKMARK = "GET_BOOKMARK";
const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";

const GET_NOTIFICATION = "GET_NOTIFICATION";
 
 

 

export { GET_ALL_MOVIES , GET_MOVIES_SELECTED , GET_GENRES_MOVIES,GET_QUERY,QUERY_INPUT, GET_MOVIES_GENRES_SELECTED, ADD_BOOKMARK, REMOVE_BOOKMARK, GET_BOOKMARK, GET_NOTIFICATION};
 